"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.User = exports.UserRole = void 0;
var typeorm_1 = require("typeorm");
var mfa_entity_1 = require("./mfa.entity");
var session_entity_1 = require("./session.entity");
var audit_log_entity_1 = require("../../common/audit/audit-log.entity");
var UserRole;
(function (UserRole) {
    UserRole["ADMIN"] = "admin";
    UserRole["PHYSICIAN"] = "physician";
    UserRole["NURSE"] = "nurse";
    UserRole["PATIENT"] = "patient";
    UserRole["BILLING_STAFF"] = "billing_staff";
    UserRole["MEDICAL_RECORDS"] = "medical_records";
})(UserRole || (exports.UserRole = UserRole = {}));
var User = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('users')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _email_decorators;
    var _email_initializers = [];
    var _email_extraInitializers = [];
    var _passwordHash_decorators;
    var _passwordHash_initializers = [];
    var _passwordHash_extraInitializers = [];
    var _firstName_decorators;
    var _firstName_initializers = [];
    var _firstName_extraInitializers = [];
    var _lastName_decorators;
    var _lastName_initializers = [];
    var _lastName_extraInitializers = [];
    var _role_decorators;
    var _role_initializers = [];
    var _role_extraInitializers = [];
    var _isActive_decorators;
    var _isActive_initializers = [];
    var _isActive_extraInitializers = [];
    var _mfaEnabled_decorators;
    var _mfaEnabled_initializers = [];
    var _mfaEnabled_extraInitializers = [];
    var _mfaSecret_decorators;
    var _mfaSecret_initializers = [];
    var _mfaSecret_extraInitializers = [];
    var _lastPasswordChangeAt_decorators;
    var _lastPasswordChangeAt_initializers = [];
    var _lastPasswordChangeAt_extraInitializers = [];
    var _failedLoginAttempts_decorators;
    var _failedLoginAttempts_initializers = [];
    var _failedLoginAttempts_extraInitializers = [];
    var _lastLoginAt_decorators;
    var _lastLoginAt_initializers = [];
    var _lastLoginAt_extraInitializers = [];
    var _lockedUntil_decorators;
    var _lockedUntil_initializers = [];
    var _lockedUntil_extraInitializers = [];
    var _requiresPasswordChange_decorators;
    var _requiresPasswordChange_initializers = [];
    var _requiresPasswordChange_extraInitializers = [];
    var _licenseNumber_decorators;
    var _licenseNumber_initializers = [];
    var _licenseNumber_extraInitializers = [];
    var _npi_decorators;
    var _npi_initializers = [];
    var _npi_extraInitializers = [];
    var _specialization_decorators;
    var _specialization_initializers = [];
    var _specialization_extraInitializers = [];
    var _permissions_decorators;
    var _permissions_initializers = [];
    var _permissions_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var _deletedAt_decorators;
    var _deletedAt_initializers = [];
    var _deletedAt_extraInitializers = [];
    var _mfaDevices_decorators;
    var _mfaDevices_initializers = [];
    var _mfaDevices_extraInitializers = [];
    var _sessions_decorators;
    var _sessions_initializers = [];
    var _sessions_extraInitializers = [];
    var _auditLogs_decorators;
    var _auditLogs_initializers = [];
    var _auditLogs_extraInitializers = [];
    var User = _classThis = /** @class */ (function () {
        function User_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.email = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _email_initializers, void 0));
            this.passwordHash = (__runInitializers(this, _email_extraInitializers), __runInitializers(this, _passwordHash_initializers, void 0));
            this.firstName = (__runInitializers(this, _passwordHash_extraInitializers), __runInitializers(this, _firstName_initializers, void 0));
            this.lastName = (__runInitializers(this, _firstName_extraInitializers), __runInitializers(this, _lastName_initializers, void 0));
            this.role = (__runInitializers(this, _lastName_extraInitializers), __runInitializers(this, _role_initializers, void 0));
            this.isActive = (__runInitializers(this, _role_extraInitializers), __runInitializers(this, _isActive_initializers, void 0));
            this.mfaEnabled = (__runInitializers(this, _isActive_extraInitializers), __runInitializers(this, _mfaEnabled_initializers, void 0));
            this.mfaSecret = (__runInitializers(this, _mfaEnabled_extraInitializers), __runInitializers(this, _mfaSecret_initializers, void 0));
            this.lastPasswordChangeAt = (__runInitializers(this, _mfaSecret_extraInitializers), __runInitializers(this, _lastPasswordChangeAt_initializers, void 0));
            this.failedLoginAttempts = (__runInitializers(this, _lastPasswordChangeAt_extraInitializers), __runInitializers(this, _failedLoginAttempts_initializers, void 0));
            this.lastLoginAt = (__runInitializers(this, _failedLoginAttempts_extraInitializers), __runInitializers(this, _lastLoginAt_initializers, void 0));
            this.lockedUntil = (__runInitializers(this, _lastLoginAt_extraInitializers), __runInitializers(this, _lockedUntil_initializers, void 0));
            this.requiresPasswordChange = (__runInitializers(this, _lockedUntil_extraInitializers), __runInitializers(this, _requiresPasswordChange_initializers, void 0));
            this.licenseNumber = (__runInitializers(this, _requiresPasswordChange_extraInitializers), __runInitializers(this, _licenseNumber_initializers, void 0));
            this.npi = (__runInitializers(this, _licenseNumber_extraInitializers), __runInitializers(this, _npi_initializers, void 0));
            this.specialization = (__runInitializers(this, _npi_extraInitializers), __runInitializers(this, _specialization_initializers, void 0));
            this.permissions = (__runInitializers(this, _specialization_extraInitializers), __runInitializers(this, _permissions_initializers, void 0));
            this.createdAt = (__runInitializers(this, _permissions_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            this.deletedAt = (__runInitializers(this, _updatedAt_extraInitializers), __runInitializers(this, _deletedAt_initializers, void 0));
            this.mfaDevices = (__runInitializers(this, _deletedAt_extraInitializers), __runInitializers(this, _mfaDevices_initializers, void 0));
            this.sessions = (__runInitializers(this, _mfaDevices_extraInitializers), __runInitializers(this, _sessions_initializers, void 0));
            this.auditLogs = (__runInitializers(this, _sessions_extraInitializers), __runInitializers(this, _auditLogs_initializers, void 0));
            __runInitializers(this, _auditLogs_extraInitializers);
        }
        return User_1;
    }());
    __setFunctionName(_classThis, "User");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _email_decorators = [(0, typeorm_1.Column)({ unique: true })];
        _passwordHash_decorators = [(0, typeorm_1.Column)()];
        _firstName_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _lastName_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _role_decorators = [(0, typeorm_1.Column)({ type: 'enum', enum: UserRole, default: UserRole.PATIENT })];
        _isActive_decorators = [(0, typeorm_1.Column)({ default: false })];
        _mfaEnabled_decorators = [(0, typeorm_1.Column)({ default: false })];
        _mfaSecret_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _lastPasswordChangeAt_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _failedLoginAttempts_decorators = [(0, typeorm_1.Column)({ default: 0 })];
        _lastLoginAt_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _lockedUntil_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _requiresPasswordChange_decorators = [(0, typeorm_1.Column)({ default: false })];
        _licenseNumber_decorators = [(0, typeorm_1.Column)({ nullable: true, length: 255 })];
        _npi_decorators = [(0, typeorm_1.Column)({ nullable: true, length: 255 })];
        _specialization_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _permissions_decorators = [(0, typeorm_1.Column)({ type: 'simple-array', nullable: true })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)()];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)()];
        _deletedAt_decorators = [(0, typeorm_1.Column)({ nullable: true })];
        _mfaDevices_decorators = [(0, typeorm_1.OneToMany)(function () { return mfa_entity_1.MfaEntity; }, function (mfa) { return mfa.user; }, { cascade: true })];
        _sessions_decorators = [(0, typeorm_1.OneToMany)(function () { return session_entity_1.SessionEntity; }, function (session) { return session.user; }, { cascade: true })];
        _auditLogs_decorators = [(0, typeorm_1.OneToMany)(function () { return audit_log_entity_1.AuditLogEntity; }, function (log) { return log.user; })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _email_decorators, { kind: "field", name: "email", static: false, private: false, access: { has: function (obj) { return "email" in obj; }, get: function (obj) { return obj.email; }, set: function (obj, value) { obj.email = value; } }, metadata: _metadata }, _email_initializers, _email_extraInitializers);
        __esDecorate(null, null, _passwordHash_decorators, { kind: "field", name: "passwordHash", static: false, private: false, access: { has: function (obj) { return "passwordHash" in obj; }, get: function (obj) { return obj.passwordHash; }, set: function (obj, value) { obj.passwordHash = value; } }, metadata: _metadata }, _passwordHash_initializers, _passwordHash_extraInitializers);
        __esDecorate(null, null, _firstName_decorators, { kind: "field", name: "firstName", static: false, private: false, access: { has: function (obj) { return "firstName" in obj; }, get: function (obj) { return obj.firstName; }, set: function (obj, value) { obj.firstName = value; } }, metadata: _metadata }, _firstName_initializers, _firstName_extraInitializers);
        __esDecorate(null, null, _lastName_decorators, { kind: "field", name: "lastName", static: false, private: false, access: { has: function (obj) { return "lastName" in obj; }, get: function (obj) { return obj.lastName; }, set: function (obj, value) { obj.lastName = value; } }, metadata: _metadata }, _lastName_initializers, _lastName_extraInitializers);
        __esDecorate(null, null, _role_decorators, { kind: "field", name: "role", static: false, private: false, access: { has: function (obj) { return "role" in obj; }, get: function (obj) { return obj.role; }, set: function (obj, value) { obj.role = value; } }, metadata: _metadata }, _role_initializers, _role_extraInitializers);
        __esDecorate(null, null, _isActive_decorators, { kind: "field", name: "isActive", static: false, private: false, access: { has: function (obj) { return "isActive" in obj; }, get: function (obj) { return obj.isActive; }, set: function (obj, value) { obj.isActive = value; } }, metadata: _metadata }, _isActive_initializers, _isActive_extraInitializers);
        __esDecorate(null, null, _mfaEnabled_decorators, { kind: "field", name: "mfaEnabled", static: false, private: false, access: { has: function (obj) { return "mfaEnabled" in obj; }, get: function (obj) { return obj.mfaEnabled; }, set: function (obj, value) { obj.mfaEnabled = value; } }, metadata: _metadata }, _mfaEnabled_initializers, _mfaEnabled_extraInitializers);
        __esDecorate(null, null, _mfaSecret_decorators, { kind: "field", name: "mfaSecret", static: false, private: false, access: { has: function (obj) { return "mfaSecret" in obj; }, get: function (obj) { return obj.mfaSecret; }, set: function (obj, value) { obj.mfaSecret = value; } }, metadata: _metadata }, _mfaSecret_initializers, _mfaSecret_extraInitializers);
        __esDecorate(null, null, _lastPasswordChangeAt_decorators, { kind: "field", name: "lastPasswordChangeAt", static: false, private: false, access: { has: function (obj) { return "lastPasswordChangeAt" in obj; }, get: function (obj) { return obj.lastPasswordChangeAt; }, set: function (obj, value) { obj.lastPasswordChangeAt = value; } }, metadata: _metadata }, _lastPasswordChangeAt_initializers, _lastPasswordChangeAt_extraInitializers);
        __esDecorate(null, null, _failedLoginAttempts_decorators, { kind: "field", name: "failedLoginAttempts", static: false, private: false, access: { has: function (obj) { return "failedLoginAttempts" in obj; }, get: function (obj) { return obj.failedLoginAttempts; }, set: function (obj, value) { obj.failedLoginAttempts = value; } }, metadata: _metadata }, _failedLoginAttempts_initializers, _failedLoginAttempts_extraInitializers);
        __esDecorate(null, null, _lastLoginAt_decorators, { kind: "field", name: "lastLoginAt", static: false, private: false, access: { has: function (obj) { return "lastLoginAt" in obj; }, get: function (obj) { return obj.lastLoginAt; }, set: function (obj, value) { obj.lastLoginAt = value; } }, metadata: _metadata }, _lastLoginAt_initializers, _lastLoginAt_extraInitializers);
        __esDecorate(null, null, _lockedUntil_decorators, { kind: "field", name: "lockedUntil", static: false, private: false, access: { has: function (obj) { return "lockedUntil" in obj; }, get: function (obj) { return obj.lockedUntil; }, set: function (obj, value) { obj.lockedUntil = value; } }, metadata: _metadata }, _lockedUntil_initializers, _lockedUntil_extraInitializers);
        __esDecorate(null, null, _requiresPasswordChange_decorators, { kind: "field", name: "requiresPasswordChange", static: false, private: false, access: { has: function (obj) { return "requiresPasswordChange" in obj; }, get: function (obj) { return obj.requiresPasswordChange; }, set: function (obj, value) { obj.requiresPasswordChange = value; } }, metadata: _metadata }, _requiresPasswordChange_initializers, _requiresPasswordChange_extraInitializers);
        __esDecorate(null, null, _licenseNumber_decorators, { kind: "field", name: "licenseNumber", static: false, private: false, access: { has: function (obj) { return "licenseNumber" in obj; }, get: function (obj) { return obj.licenseNumber; }, set: function (obj, value) { obj.licenseNumber = value; } }, metadata: _metadata }, _licenseNumber_initializers, _licenseNumber_extraInitializers);
        __esDecorate(null, null, _npi_decorators, { kind: "field", name: "npi", static: false, private: false, access: { has: function (obj) { return "npi" in obj; }, get: function (obj) { return obj.npi; }, set: function (obj, value) { obj.npi = value; } }, metadata: _metadata }, _npi_initializers, _npi_extraInitializers);
        __esDecorate(null, null, _specialization_decorators, { kind: "field", name: "specialization", static: false, private: false, access: { has: function (obj) { return "specialization" in obj; }, get: function (obj) { return obj.specialization; }, set: function (obj, value) { obj.specialization = value; } }, metadata: _metadata }, _specialization_initializers, _specialization_extraInitializers);
        __esDecorate(null, null, _permissions_decorators, { kind: "field", name: "permissions", static: false, private: false, access: { has: function (obj) { return "permissions" in obj; }, get: function (obj) { return obj.permissions; }, set: function (obj, value) { obj.permissions = value; } }, metadata: _metadata }, _permissions_initializers, _permissions_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, null, _deletedAt_decorators, { kind: "field", name: "deletedAt", static: false, private: false, access: { has: function (obj) { return "deletedAt" in obj; }, get: function (obj) { return obj.deletedAt; }, set: function (obj, value) { obj.deletedAt = value; } }, metadata: _metadata }, _deletedAt_initializers, _deletedAt_extraInitializers);
        __esDecorate(null, null, _mfaDevices_decorators, { kind: "field", name: "mfaDevices", static: false, private: false, access: { has: function (obj) { return "mfaDevices" in obj; }, get: function (obj) { return obj.mfaDevices; }, set: function (obj, value) { obj.mfaDevices = value; } }, metadata: _metadata }, _mfaDevices_initializers, _mfaDevices_extraInitializers);
        __esDecorate(null, null, _sessions_decorators, { kind: "field", name: "sessions", static: false, private: false, access: { has: function (obj) { return "sessions" in obj; }, get: function (obj) { return obj.sessions; }, set: function (obj, value) { obj.sessions = value; } }, metadata: _metadata }, _sessions_initializers, _sessions_extraInitializers);
        __esDecorate(null, null, _auditLogs_decorators, { kind: "field", name: "auditLogs", static: false, private: false, access: { has: function (obj) { return "auditLogs" in obj; }, get: function (obj) { return obj.auditLogs; }, set: function (obj, value) { obj.auditLogs = value; } }, metadata: _metadata }, _auditLogs_initializers, _auditLogs_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        User = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return User = _classThis;
}();
exports.User = User;
