"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Billing = void 0;
var typeorm_1 = require("typeorm");
var billing_line_item_entity_1 = require("./billing-line-item.entity");
var payment_entity_1 = require("./payment.entity");
var Billing = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('billings')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _invoiceNumber_decorators;
    var _invoiceNumber_initializers = [];
    var _invoiceNumber_extraInitializers = [];
    var _patientId_decorators;
    var _patientId_initializers = [];
    var _patientId_extraInitializers = [];
    var _patientName_decorators;
    var _patientName_initializers = [];
    var _patientName_extraInitializers = [];
    var _encounterId_decorators;
    var _encounterId_initializers = [];
    var _encounterId_extraInitializers = [];
    var _serviceDate_decorators;
    var _serviceDate_initializers = [];
    var _serviceDate_extraInitializers = [];
    var _providerId_decorators;
    var _providerId_initializers = [];
    var _providerId_extraInitializers = [];
    var _providerName_decorators;
    var _providerName_initializers = [];
    var _providerName_extraInitializers = [];
    var _providerNpi_decorators;
    var _providerNpi_initializers = [];
    var _providerNpi_extraInitializers = [];
    var _facilityId_decorators;
    var _facilityId_initializers = [];
    var _facilityId_extraInitializers = [];
    var _facilityName_decorators;
    var _facilityName_initializers = [];
    var _facilityName_extraInitializers = [];
    var _placeOfService_decorators;
    var _placeOfService_initializers = [];
    var _placeOfService_extraInitializers = [];
    var _totalCharges_decorators;
    var _totalCharges_initializers = [];
    var _totalCharges_extraInitializers = [];
    var _totalAdjustments_decorators;
    var _totalAdjustments_initializers = [];
    var _totalAdjustments_extraInitializers = [];
    var _totalPayments_decorators;
    var _totalPayments_initializers = [];
    var _totalPayments_extraInitializers = [];
    var _patientResponsibility_decorators;
    var _patientResponsibility_initializers = [];
    var _patientResponsibility_extraInitializers = [];
    var _insuranceResponsibility_decorators;
    var _insuranceResponsibility_initializers = [];
    var _insuranceResponsibility_extraInitializers = [];
    var _balance_decorators;
    var _balance_initializers = [];
    var _balance_extraInitializers = [];
    var _status_decorators;
    var _status_initializers = [];
    var _status_extraInitializers = [];
    var _dueDate_decorators;
    var _dueDate_initializers = [];
    var _dueDate_extraInitializers = [];
    var _isSentToCollections_decorators;
    var _isSentToCollections_initializers = [];
    var _isSentToCollections_extraInitializers = [];
    var _sentToCollectionsDate_decorators;
    var _sentToCollectionsDate_initializers = [];
    var _sentToCollectionsDate_extraInitializers = [];
    var _diagnosisCodes_decorators;
    var _diagnosisCodes_initializers = [];
    var _diagnosisCodes_extraInitializers = [];
    var _notes_decorators;
    var _notes_initializers = [];
    var _notes_extraInitializers = [];
    var _lineItems_decorators;
    var _lineItems_initializers = [];
    var _lineItems_extraInitializers = [];
    var _payments_decorators;
    var _payments_initializers = [];
    var _payments_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var Billing = _classThis = /** @class */ (function () {
        function Billing_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.invoiceNumber = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _invoiceNumber_initializers, void 0));
            this.patientId = (__runInitializers(this, _invoiceNumber_extraInitializers), __runInitializers(this, _patientId_initializers, void 0));
            this.patientName = (__runInitializers(this, _patientId_extraInitializers), __runInitializers(this, _patientName_initializers, void 0));
            this.encounterId = (__runInitializers(this, _patientName_extraInitializers), __runInitializers(this, _encounterId_initializers, void 0));
            this.serviceDate = (__runInitializers(this, _encounterId_extraInitializers), __runInitializers(this, _serviceDate_initializers, void 0));
            this.providerId = (__runInitializers(this, _serviceDate_extraInitializers), __runInitializers(this, _providerId_initializers, void 0));
            this.providerName = (__runInitializers(this, _providerId_extraInitializers), __runInitializers(this, _providerName_initializers, void 0));
            this.providerNpi = (__runInitializers(this, _providerName_extraInitializers), __runInitializers(this, _providerNpi_initializers, void 0));
            this.facilityId = (__runInitializers(this, _providerNpi_extraInitializers), __runInitializers(this, _facilityId_initializers, void 0));
            this.facilityName = (__runInitializers(this, _facilityId_extraInitializers), __runInitializers(this, _facilityName_initializers, void 0));
            this.placeOfService = (__runInitializers(this, _facilityName_extraInitializers), __runInitializers(this, _placeOfService_initializers, void 0));
            this.totalCharges = (__runInitializers(this, _placeOfService_extraInitializers), __runInitializers(this, _totalCharges_initializers, void 0));
            this.totalAdjustments = (__runInitializers(this, _totalCharges_extraInitializers), __runInitializers(this, _totalAdjustments_initializers, void 0));
            this.totalPayments = (__runInitializers(this, _totalAdjustments_extraInitializers), __runInitializers(this, _totalPayments_initializers, void 0));
            this.patientResponsibility = (__runInitializers(this, _totalPayments_extraInitializers), __runInitializers(this, _patientResponsibility_initializers, void 0));
            this.insuranceResponsibility = (__runInitializers(this, _patientResponsibility_extraInitializers), __runInitializers(this, _insuranceResponsibility_initializers, void 0));
            this.balance = (__runInitializers(this, _insuranceResponsibility_extraInitializers), __runInitializers(this, _balance_initializers, void 0));
            this.status = (__runInitializers(this, _balance_extraInitializers), __runInitializers(this, _status_initializers, void 0));
            this.dueDate = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _dueDate_initializers, void 0));
            this.isSentToCollections = (__runInitializers(this, _dueDate_extraInitializers), __runInitializers(this, _isSentToCollections_initializers, void 0));
            this.sentToCollectionsDate = (__runInitializers(this, _isSentToCollections_extraInitializers), __runInitializers(this, _sentToCollectionsDate_initializers, void 0));
            this.diagnosisCodes = (__runInitializers(this, _sentToCollectionsDate_extraInitializers), __runInitializers(this, _diagnosisCodes_initializers, void 0));
            this.notes = (__runInitializers(this, _diagnosisCodes_extraInitializers), __runInitializers(this, _notes_initializers, void 0));
            this.lineItems = (__runInitializers(this, _notes_extraInitializers), __runInitializers(this, _lineItems_initializers, void 0));
            this.payments = (__runInitializers(this, _lineItems_extraInitializers), __runInitializers(this, _payments_initializers, void 0));
            this.createdAt = (__runInitializers(this, _payments_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            __runInitializers(this, _updatedAt_extraInitializers);
        }
        return Billing_1;
    }());
    __setFunctionName(_classThis, "Billing");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _invoiceNumber_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 50, unique: true }), (0, typeorm_1.Index)()];
        _patientId_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 100 }), (0, typeorm_1.Index)()];
        _patientName_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 200 })];
        _encounterId_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 100, nullable: true })];
        _serviceDate_decorators = [(0, typeorm_1.Column)({ type: 'date' })];
        _providerId_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 100 })];
        _providerName_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 200 })];
        _providerNpi_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 20, nullable: true })];
        _facilityId_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 100, nullable: true })];
        _facilityName_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 200, nullable: true })];
        _placeOfService_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 10, nullable: true })];
        _totalCharges_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _totalAdjustments_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _totalPayments_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _patientResponsibility_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _insuranceResponsibility_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _balance_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _status_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 20, default: 'open' })];
        _dueDate_decorators = [(0, typeorm_1.Column)({ type: 'date', nullable: true })];
        _isSentToCollections_decorators = [(0, typeorm_1.Column)({ type: 'boolean', default: false })];
        _sentToCollectionsDate_decorators = [(0, typeorm_1.Column)({ type: 'date', nullable: true })];
        _diagnosisCodes_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _notes_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _lineItems_decorators = [(0, typeorm_1.OneToMany)(function () { return billing_line_item_entity_1.BillingLineItem; }, function (lineItem) { return lineItem.billing; }, {
                cascade: true,
            })];
        _payments_decorators = [(0, typeorm_1.OneToMany)(function () { return payment_entity_1.Payment; }, function (payment) { return payment.billing; })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)()];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)()];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _invoiceNumber_decorators, { kind: "field", name: "invoiceNumber", static: false, private: false, access: { has: function (obj) { return "invoiceNumber" in obj; }, get: function (obj) { return obj.invoiceNumber; }, set: function (obj, value) { obj.invoiceNumber = value; } }, metadata: _metadata }, _invoiceNumber_initializers, _invoiceNumber_extraInitializers);
        __esDecorate(null, null, _patientId_decorators, { kind: "field", name: "patientId", static: false, private: false, access: { has: function (obj) { return "patientId" in obj; }, get: function (obj) { return obj.patientId; }, set: function (obj, value) { obj.patientId = value; } }, metadata: _metadata }, _patientId_initializers, _patientId_extraInitializers);
        __esDecorate(null, null, _patientName_decorators, { kind: "field", name: "patientName", static: false, private: false, access: { has: function (obj) { return "patientName" in obj; }, get: function (obj) { return obj.patientName; }, set: function (obj, value) { obj.patientName = value; } }, metadata: _metadata }, _patientName_initializers, _patientName_extraInitializers);
        __esDecorate(null, null, _encounterId_decorators, { kind: "field", name: "encounterId", static: false, private: false, access: { has: function (obj) { return "encounterId" in obj; }, get: function (obj) { return obj.encounterId; }, set: function (obj, value) { obj.encounterId = value; } }, metadata: _metadata }, _encounterId_initializers, _encounterId_extraInitializers);
        __esDecorate(null, null, _serviceDate_decorators, { kind: "field", name: "serviceDate", static: false, private: false, access: { has: function (obj) { return "serviceDate" in obj; }, get: function (obj) { return obj.serviceDate; }, set: function (obj, value) { obj.serviceDate = value; } }, metadata: _metadata }, _serviceDate_initializers, _serviceDate_extraInitializers);
        __esDecorate(null, null, _providerId_decorators, { kind: "field", name: "providerId", static: false, private: false, access: { has: function (obj) { return "providerId" in obj; }, get: function (obj) { return obj.providerId; }, set: function (obj, value) { obj.providerId = value; } }, metadata: _metadata }, _providerId_initializers, _providerId_extraInitializers);
        __esDecorate(null, null, _providerName_decorators, { kind: "field", name: "providerName", static: false, private: false, access: { has: function (obj) { return "providerName" in obj; }, get: function (obj) { return obj.providerName; }, set: function (obj, value) { obj.providerName = value; } }, metadata: _metadata }, _providerName_initializers, _providerName_extraInitializers);
        __esDecorate(null, null, _providerNpi_decorators, { kind: "field", name: "providerNpi", static: false, private: false, access: { has: function (obj) { return "providerNpi" in obj; }, get: function (obj) { return obj.providerNpi; }, set: function (obj, value) { obj.providerNpi = value; } }, metadata: _metadata }, _providerNpi_initializers, _providerNpi_extraInitializers);
        __esDecorate(null, null, _facilityId_decorators, { kind: "field", name: "facilityId", static: false, private: false, access: { has: function (obj) { return "facilityId" in obj; }, get: function (obj) { return obj.facilityId; }, set: function (obj, value) { obj.facilityId = value; } }, metadata: _metadata }, _facilityId_initializers, _facilityId_extraInitializers);
        __esDecorate(null, null, _facilityName_decorators, { kind: "field", name: "facilityName", static: false, private: false, access: { has: function (obj) { return "facilityName" in obj; }, get: function (obj) { return obj.facilityName; }, set: function (obj, value) { obj.facilityName = value; } }, metadata: _metadata }, _facilityName_initializers, _facilityName_extraInitializers);
        __esDecorate(null, null, _placeOfService_decorators, { kind: "field", name: "placeOfService", static: false, private: false, access: { has: function (obj) { return "placeOfService" in obj; }, get: function (obj) { return obj.placeOfService; }, set: function (obj, value) { obj.placeOfService = value; } }, metadata: _metadata }, _placeOfService_initializers, _placeOfService_extraInitializers);
        __esDecorate(null, null, _totalCharges_decorators, { kind: "field", name: "totalCharges", static: false, private: false, access: { has: function (obj) { return "totalCharges" in obj; }, get: function (obj) { return obj.totalCharges; }, set: function (obj, value) { obj.totalCharges = value; } }, metadata: _metadata }, _totalCharges_initializers, _totalCharges_extraInitializers);
        __esDecorate(null, null, _totalAdjustments_decorators, { kind: "field", name: "totalAdjustments", static: false, private: false, access: { has: function (obj) { return "totalAdjustments" in obj; }, get: function (obj) { return obj.totalAdjustments; }, set: function (obj, value) { obj.totalAdjustments = value; } }, metadata: _metadata }, _totalAdjustments_initializers, _totalAdjustments_extraInitializers);
        __esDecorate(null, null, _totalPayments_decorators, { kind: "field", name: "totalPayments", static: false, private: false, access: { has: function (obj) { return "totalPayments" in obj; }, get: function (obj) { return obj.totalPayments; }, set: function (obj, value) { obj.totalPayments = value; } }, metadata: _metadata }, _totalPayments_initializers, _totalPayments_extraInitializers);
        __esDecorate(null, null, _patientResponsibility_decorators, { kind: "field", name: "patientResponsibility", static: false, private: false, access: { has: function (obj) { return "patientResponsibility" in obj; }, get: function (obj) { return obj.patientResponsibility; }, set: function (obj, value) { obj.patientResponsibility = value; } }, metadata: _metadata }, _patientResponsibility_initializers, _patientResponsibility_extraInitializers);
        __esDecorate(null, null, _insuranceResponsibility_decorators, { kind: "field", name: "insuranceResponsibility", static: false, private: false, access: { has: function (obj) { return "insuranceResponsibility" in obj; }, get: function (obj) { return obj.insuranceResponsibility; }, set: function (obj, value) { obj.insuranceResponsibility = value; } }, metadata: _metadata }, _insuranceResponsibility_initializers, _insuranceResponsibility_extraInitializers);
        __esDecorate(null, null, _balance_decorators, { kind: "field", name: "balance", static: false, private: false, access: { has: function (obj) { return "balance" in obj; }, get: function (obj) { return obj.balance; }, set: function (obj, value) { obj.balance = value; } }, metadata: _metadata }, _balance_initializers, _balance_extraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: function (obj) { return "status" in obj; }, get: function (obj) { return obj.status; }, set: function (obj, value) { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
        __esDecorate(null, null, _dueDate_decorators, { kind: "field", name: "dueDate", static: false, private: false, access: { has: function (obj) { return "dueDate" in obj; }, get: function (obj) { return obj.dueDate; }, set: function (obj, value) { obj.dueDate = value; } }, metadata: _metadata }, _dueDate_initializers, _dueDate_extraInitializers);
        __esDecorate(null, null, _isSentToCollections_decorators, { kind: "field", name: "isSentToCollections", static: false, private: false, access: { has: function (obj) { return "isSentToCollections" in obj; }, get: function (obj) { return obj.isSentToCollections; }, set: function (obj, value) { obj.isSentToCollections = value; } }, metadata: _metadata }, _isSentToCollections_initializers, _isSentToCollections_extraInitializers);
        __esDecorate(null, null, _sentToCollectionsDate_decorators, { kind: "field", name: "sentToCollectionsDate", static: false, private: false, access: { has: function (obj) { return "sentToCollectionsDate" in obj; }, get: function (obj) { return obj.sentToCollectionsDate; }, set: function (obj, value) { obj.sentToCollectionsDate = value; } }, metadata: _metadata }, _sentToCollectionsDate_initializers, _sentToCollectionsDate_extraInitializers);
        __esDecorate(null, null, _diagnosisCodes_decorators, { kind: "field", name: "diagnosisCodes", static: false, private: false, access: { has: function (obj) { return "diagnosisCodes" in obj; }, get: function (obj) { return obj.diagnosisCodes; }, set: function (obj, value) { obj.diagnosisCodes = value; } }, metadata: _metadata }, _diagnosisCodes_initializers, _diagnosisCodes_extraInitializers);
        __esDecorate(null, null, _notes_decorators, { kind: "field", name: "notes", static: false, private: false, access: { has: function (obj) { return "notes" in obj; }, get: function (obj) { return obj.notes; }, set: function (obj, value) { obj.notes = value; } }, metadata: _metadata }, _notes_initializers, _notes_extraInitializers);
        __esDecorate(null, null, _lineItems_decorators, { kind: "field", name: "lineItems", static: false, private: false, access: { has: function (obj) { return "lineItems" in obj; }, get: function (obj) { return obj.lineItems; }, set: function (obj, value) { obj.lineItems = value; } }, metadata: _metadata }, _lineItems_initializers, _lineItems_extraInitializers);
        __esDecorate(null, null, _payments_decorators, { kind: "field", name: "payments", static: false, private: false, access: { has: function (obj) { return "payments" in obj; }, get: function (obj) { return obj.payments; }, set: function (obj, value) { obj.payments = value; } }, metadata: _metadata }, _payments_initializers, _payments_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        Billing = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return Billing = _classThis;
}();
exports.Billing = Billing;
