"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.BillingLineItem = void 0;
var typeorm_1 = require("typeorm");
var billing_entity_1 = require("./billing.entity");
var BillingLineItem = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('billing_line_items')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _billingId_decorators;
    var _billingId_initializers = [];
    var _billingId_extraInitializers = [];
    var _billing_decorators;
    var _billing_initializers = [];
    var _billing_extraInitializers = [];
    var _lineNumber_decorators;
    var _lineNumber_initializers = [];
    var _lineNumber_extraInitializers = [];
    var _serviceDate_decorators;
    var _serviceDate_initializers = [];
    var _serviceDate_extraInitializers = [];
    var _serviceDateEnd_decorators;
    var _serviceDateEnd_initializers = [];
    var _serviceDateEnd_extraInitializers = [];
    var _cptCode_decorators;
    var _cptCode_initializers = [];
    var _cptCode_extraInitializers = [];
    var _cptDescription_decorators;
    var _cptDescription_initializers = [];
    var _cptDescription_extraInitializers = [];
    var _modifiers_decorators;
    var _modifiers_initializers = [];
    var _modifiers_extraInitializers = [];
    var _diagnosisCodes_decorators;
    var _diagnosisCodes_initializers = [];
    var _diagnosisCodes_extraInitializers = [];
    var _units_decorators;
    var _units_initializers = [];
    var _units_extraInitializers = [];
    var _unitCharge_decorators;
    var _unitCharge_initializers = [];
    var _unitCharge_extraInitializers = [];
    var _totalCharge_decorators;
    var _totalCharge_initializers = [];
    var _totalCharge_extraInitializers = [];
    var _allowedAmount_decorators;
    var _allowedAmount_initializers = [];
    var _allowedAmount_extraInitializers = [];
    var _adjustmentAmount_decorators;
    var _adjustmentAmount_initializers = [];
    var _adjustmentAmount_extraInitializers = [];
    var _paidAmount_decorators;
    var _paidAmount_initializers = [];
    var _paidAmount_extraInitializers = [];
    var _patientResponsibility_decorators;
    var _patientResponsibility_initializers = [];
    var _patientResponsibility_extraInitializers = [];
    var _revenueCode_decorators;
    var _revenueCode_initializers = [];
    var _revenueCode_extraInitializers = [];
    var _ndc_decorators;
    var _ndc_initializers = [];
    var _ndc_extraInitializers = [];
    var _notes_decorators;
    var _notes_initializers = [];
    var _notes_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var BillingLineItem = _classThis = /** @class */ (function () {
        function BillingLineItem_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.billingId = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _billingId_initializers, void 0));
            this.billing = (__runInitializers(this, _billingId_extraInitializers), __runInitializers(this, _billing_initializers, void 0));
            this.lineNumber = (__runInitializers(this, _billing_extraInitializers), __runInitializers(this, _lineNumber_initializers, void 0));
            this.serviceDate = (__runInitializers(this, _lineNumber_extraInitializers), __runInitializers(this, _serviceDate_initializers, void 0));
            this.serviceDateEnd = (__runInitializers(this, _serviceDate_extraInitializers), __runInitializers(this, _serviceDateEnd_initializers, void 0));
            this.cptCode = (__runInitializers(this, _serviceDateEnd_extraInitializers), __runInitializers(this, _cptCode_initializers, void 0));
            this.cptDescription = (__runInitializers(this, _cptCode_extraInitializers), __runInitializers(this, _cptDescription_initializers, void 0));
            this.modifiers = (__runInitializers(this, _cptDescription_extraInitializers), __runInitializers(this, _modifiers_initializers, void 0));
            this.diagnosisCodes = (__runInitializers(this, _modifiers_extraInitializers), __runInitializers(this, _diagnosisCodes_initializers, void 0));
            this.units = (__runInitializers(this, _diagnosisCodes_extraInitializers), __runInitializers(this, _units_initializers, void 0));
            this.unitCharge = (__runInitializers(this, _units_extraInitializers), __runInitializers(this, _unitCharge_initializers, void 0));
            this.totalCharge = (__runInitializers(this, _unitCharge_extraInitializers), __runInitializers(this, _totalCharge_initializers, void 0));
            this.allowedAmount = (__runInitializers(this, _totalCharge_extraInitializers), __runInitializers(this, _allowedAmount_initializers, void 0));
            this.adjustmentAmount = (__runInitializers(this, _allowedAmount_extraInitializers), __runInitializers(this, _adjustmentAmount_initializers, void 0));
            this.paidAmount = (__runInitializers(this, _adjustmentAmount_extraInitializers), __runInitializers(this, _paidAmount_initializers, void 0));
            this.patientResponsibility = (__runInitializers(this, _paidAmount_extraInitializers), __runInitializers(this, _patientResponsibility_initializers, void 0));
            this.revenueCode = (__runInitializers(this, _patientResponsibility_extraInitializers), __runInitializers(this, _revenueCode_initializers, void 0));
            this.ndc = (__runInitializers(this, _revenueCode_extraInitializers), __runInitializers(this, _ndc_initializers, void 0));
            this.notes = (__runInitializers(this, _ndc_extraInitializers), __runInitializers(this, _notes_initializers, void 0));
            this.createdAt = (__runInitializers(this, _notes_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            __runInitializers(this, _updatedAt_extraInitializers);
        }
        return BillingLineItem_1;
    }());
    __setFunctionName(_classThis, "BillingLineItem");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _billingId_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 100 }), (0, typeorm_1.Index)()];
        _billing_decorators = [(0, typeorm_1.ManyToOne)(function () { return billing_entity_1.Billing; }, function (billing) { return billing.lineItems; }), (0, typeorm_1.JoinColumn)({ name: 'billingId' })];
        _lineNumber_decorators = [(0, typeorm_1.Column)({ type: 'integer' })];
        _serviceDate_decorators = [(0, typeorm_1.Column)({ type: 'date' })];
        _serviceDateEnd_decorators = [(0, typeorm_1.Column)({ type: 'date', nullable: true })];
        _cptCode_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 10 })];
        _cptDescription_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 200 })];
        _modifiers_decorators = [(0, typeorm_1.Column)({ type: 'simple-array', nullable: true })];
        _diagnosisCodes_decorators = [(0, typeorm_1.Column)({ type: 'simple-array', nullable: true })];
        _units_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 8, scale: 2, default: 1 })];
        _unitCharge_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2 })];
        _totalCharge_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2 })];
        _allowedAmount_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _adjustmentAmount_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _paidAmount_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _patientResponsibility_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _revenueCode_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 10, nullable: true })];
        _ndc_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 20, nullable: true })];
        _notes_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)()];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)()];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _billingId_decorators, { kind: "field", name: "billingId", static: false, private: false, access: { has: function (obj) { return "billingId" in obj; }, get: function (obj) { return obj.billingId; }, set: function (obj, value) { obj.billingId = value; } }, metadata: _metadata }, _billingId_initializers, _billingId_extraInitializers);
        __esDecorate(null, null, _billing_decorators, { kind: "field", name: "billing", static: false, private: false, access: { has: function (obj) { return "billing" in obj; }, get: function (obj) { return obj.billing; }, set: function (obj, value) { obj.billing = value; } }, metadata: _metadata }, _billing_initializers, _billing_extraInitializers);
        __esDecorate(null, null, _lineNumber_decorators, { kind: "field", name: "lineNumber", static: false, private: false, access: { has: function (obj) { return "lineNumber" in obj; }, get: function (obj) { return obj.lineNumber; }, set: function (obj, value) { obj.lineNumber = value; } }, metadata: _metadata }, _lineNumber_initializers, _lineNumber_extraInitializers);
        __esDecorate(null, null, _serviceDate_decorators, { kind: "field", name: "serviceDate", static: false, private: false, access: { has: function (obj) { return "serviceDate" in obj; }, get: function (obj) { return obj.serviceDate; }, set: function (obj, value) { obj.serviceDate = value; } }, metadata: _metadata }, _serviceDate_initializers, _serviceDate_extraInitializers);
        __esDecorate(null, null, _serviceDateEnd_decorators, { kind: "field", name: "serviceDateEnd", static: false, private: false, access: { has: function (obj) { return "serviceDateEnd" in obj; }, get: function (obj) { return obj.serviceDateEnd; }, set: function (obj, value) { obj.serviceDateEnd = value; } }, metadata: _metadata }, _serviceDateEnd_initializers, _serviceDateEnd_extraInitializers);
        __esDecorate(null, null, _cptCode_decorators, { kind: "field", name: "cptCode", static: false, private: false, access: { has: function (obj) { return "cptCode" in obj; }, get: function (obj) { return obj.cptCode; }, set: function (obj, value) { obj.cptCode = value; } }, metadata: _metadata }, _cptCode_initializers, _cptCode_extraInitializers);
        __esDecorate(null, null, _cptDescription_decorators, { kind: "field", name: "cptDescription", static: false, private: false, access: { has: function (obj) { return "cptDescription" in obj; }, get: function (obj) { return obj.cptDescription; }, set: function (obj, value) { obj.cptDescription = value; } }, metadata: _metadata }, _cptDescription_initializers, _cptDescription_extraInitializers);
        __esDecorate(null, null, _modifiers_decorators, { kind: "field", name: "modifiers", static: false, private: false, access: { has: function (obj) { return "modifiers" in obj; }, get: function (obj) { return obj.modifiers; }, set: function (obj, value) { obj.modifiers = value; } }, metadata: _metadata }, _modifiers_initializers, _modifiers_extraInitializers);
        __esDecorate(null, null, _diagnosisCodes_decorators, { kind: "field", name: "diagnosisCodes", static: false, private: false, access: { has: function (obj) { return "diagnosisCodes" in obj; }, get: function (obj) { return obj.diagnosisCodes; }, set: function (obj, value) { obj.diagnosisCodes = value; } }, metadata: _metadata }, _diagnosisCodes_initializers, _diagnosisCodes_extraInitializers);
        __esDecorate(null, null, _units_decorators, { kind: "field", name: "units", static: false, private: false, access: { has: function (obj) { return "units" in obj; }, get: function (obj) { return obj.units; }, set: function (obj, value) { obj.units = value; } }, metadata: _metadata }, _units_initializers, _units_extraInitializers);
        __esDecorate(null, null, _unitCharge_decorators, { kind: "field", name: "unitCharge", static: false, private: false, access: { has: function (obj) { return "unitCharge" in obj; }, get: function (obj) { return obj.unitCharge; }, set: function (obj, value) { obj.unitCharge = value; } }, metadata: _metadata }, _unitCharge_initializers, _unitCharge_extraInitializers);
        __esDecorate(null, null, _totalCharge_decorators, { kind: "field", name: "totalCharge", static: false, private: false, access: { has: function (obj) { return "totalCharge" in obj; }, get: function (obj) { return obj.totalCharge; }, set: function (obj, value) { obj.totalCharge = value; } }, metadata: _metadata }, _totalCharge_initializers, _totalCharge_extraInitializers);
        __esDecorate(null, null, _allowedAmount_decorators, { kind: "field", name: "allowedAmount", static: false, private: false, access: { has: function (obj) { return "allowedAmount" in obj; }, get: function (obj) { return obj.allowedAmount; }, set: function (obj, value) { obj.allowedAmount = value; } }, metadata: _metadata }, _allowedAmount_initializers, _allowedAmount_extraInitializers);
        __esDecorate(null, null, _adjustmentAmount_decorators, { kind: "field", name: "adjustmentAmount", static: false, private: false, access: { has: function (obj) { return "adjustmentAmount" in obj; }, get: function (obj) { return obj.adjustmentAmount; }, set: function (obj, value) { obj.adjustmentAmount = value; } }, metadata: _metadata }, _adjustmentAmount_initializers, _adjustmentAmount_extraInitializers);
        __esDecorate(null, null, _paidAmount_decorators, { kind: "field", name: "paidAmount", static: false, private: false, access: { has: function (obj) { return "paidAmount" in obj; }, get: function (obj) { return obj.paidAmount; }, set: function (obj, value) { obj.paidAmount = value; } }, metadata: _metadata }, _paidAmount_initializers, _paidAmount_extraInitializers);
        __esDecorate(null, null, _patientResponsibility_decorators, { kind: "field", name: "patientResponsibility", static: false, private: false, access: { has: function (obj) { return "patientResponsibility" in obj; }, get: function (obj) { return obj.patientResponsibility; }, set: function (obj, value) { obj.patientResponsibility = value; } }, metadata: _metadata }, _patientResponsibility_initializers, _patientResponsibility_extraInitializers);
        __esDecorate(null, null, _revenueCode_decorators, { kind: "field", name: "revenueCode", static: false, private: false, access: { has: function (obj) { return "revenueCode" in obj; }, get: function (obj) { return obj.revenueCode; }, set: function (obj, value) { obj.revenueCode = value; } }, metadata: _metadata }, _revenueCode_initializers, _revenueCode_extraInitializers);
        __esDecorate(null, null, _ndc_decorators, { kind: "field", name: "ndc", static: false, private: false, access: { has: function (obj) { return "ndc" in obj; }, get: function (obj) { return obj.ndc; }, set: function (obj, value) { obj.ndc = value; } }, metadata: _metadata }, _ndc_initializers, _ndc_extraInitializers);
        __esDecorate(null, null, _notes_decorators, { kind: "field", name: "notes", static: false, private: false, access: { has: function (obj) { return "notes" in obj; }, get: function (obj) { return obj.notes; }, set: function (obj, value) { obj.notes = value; } }, metadata: _metadata }, _notes_initializers, _notes_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        BillingLineItem = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return BillingLineItem = _classThis;
}();
exports.BillingLineItem = BillingLineItem;
