"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.InsuranceClaim = void 0;
var typeorm_1 = require("typeorm");
var enums_1 = require("../../common/enums");
var insurance_entity_1 = require("./insurance.entity");
var claim_denial_entity_1 = require("./claim-denial.entity");
var InsuranceClaim = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('insurance_claims')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _claimNumber_decorators;
    var _claimNumber_initializers = [];
    var _claimNumber_extraInitializers = [];
    var _billingId_decorators;
    var _billingId_initializers = [];
    var _billingId_extraInitializers = [];
    var _insuranceId_decorators;
    var _insuranceId_initializers = [];
    var _insuranceId_extraInitializers = [];
    var _insurance_decorators;
    var _insurance_initializers = [];
    var _insurance_extraInitializers = [];
    var _patientId_decorators;
    var _patientId_initializers = [];
    var _patientId_extraInitializers = [];
    var _claimType_decorators;
    var _claimType_initializers = [];
    var _claimType_extraInitializers = [];
    var _status_decorators;
    var _status_initializers = [];
    var _status_extraInitializers = [];
    var _payerClaimNumber_decorators;
    var _payerClaimNumber_initializers = [];
    var _payerClaimNumber_extraInitializers = [];
    var _clearinghouseClaimId_decorators;
    var _clearinghouseClaimId_initializers = [];
    var _clearinghouseClaimId_extraInitializers = [];
    var _serviceStartDate_decorators;
    var _serviceStartDate_initializers = [];
    var _serviceStartDate_extraInitializers = [];
    var _serviceEndDate_decorators;
    var _serviceEndDate_initializers = [];
    var _serviceEndDate_extraInitializers = [];
    var _submittedAt_decorators;
    var _submittedAt_initializers = [];
    var _submittedAt_extraInitializers = [];
    var _acceptedAt_decorators;
    var _acceptedAt_initializers = [];
    var _acceptedAt_extraInitializers = [];
    var _adjudicatedAt_decorators;
    var _adjudicatedAt_initializers = [];
    var _adjudicatedAt_extraInitializers = [];
    var _billedAmount_decorators;
    var _billedAmount_initializers = [];
    var _billedAmount_extraInitializers = [];
    var _allowedAmount_decorators;
    var _allowedAmount_initializers = [];
    var _allowedAmount_extraInitializers = [];
    var _paidAmount_decorators;
    var _paidAmount_initializers = [];
    var _paidAmount_extraInitializers = [];
    var _adjustmentAmount_decorators;
    var _adjustmentAmount_initializers = [];
    var _adjustmentAmount_extraInitializers = [];
    var _patientResponsibility_decorators;
    var _patientResponsibility_initializers = [];
    var _patientResponsibility_extraInitializers = [];
    var _coinsuranceAmount_decorators;
    var _coinsuranceAmount_initializers = [];
    var _coinsuranceAmount_extraInitializers = [];
    var _copayAmount_decorators;
    var _copayAmount_initializers = [];
    var _copayAmount_extraInitializers = [];
    var _deductibleAmount_decorators;
    var _deductibleAmount_initializers = [];
    var _deductibleAmount_extraInitializers = [];
    var _diagnosisCodes_decorators;
    var _diagnosisCodes_initializers = [];
    var _diagnosisCodes_extraInitializers = [];
    var _procedureCodes_decorators;
    var _procedureCodes_initializers = [];
    var _procedureCodes_extraInitializers = [];
    var _provider_decorators;
    var _provider_initializers = [];
    var _provider_extraInitializers = [];
    var _facility_decorators;
    var _facility_initializers = [];
    var _facility_extraInitializers = [];
    var _subscriber_decorators;
    var _subscriber_initializers = [];
    var _subscriber_extraInitializers = [];
    var _patient_decorators;
    var _patient_initializers = [];
    var _patient_extraInitializers = [];
    var _edi837Payload_decorators;
    var _edi837Payload_initializers = [];
    var _edi837Payload_extraInitializers = [];
    var _edi835Response_decorators;
    var _edi835Response_initializers = [];
    var _edi835Response_extraInitializers = [];
    var _submissionHistory_decorators;
    var _submissionHistory_initializers = [];
    var _submissionHistory_extraInitializers = [];
    var _remarkCodes_decorators;
    var _remarkCodes_initializers = [];
    var _remarkCodes_extraInitializers = [];
    var _adjustmentCodes_decorators;
    var _adjustmentCodes_initializers = [];
    var _adjustmentCodes_extraInitializers = [];
    var _notes_decorators;
    var _notes_initializers = [];
    var _notes_extraInitializers = [];
    var _submissionAttempts_decorators;
    var _submissionAttempts_initializers = [];
    var _submissionAttempts_extraInitializers = [];
    var _timelyFilingDeadline_decorators;
    var _timelyFilingDeadline_initializers = [];
    var _timelyFilingDeadline_extraInitializers = [];
    var _denials_decorators;
    var _denials_initializers = [];
    var _denials_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var InsuranceClaim = _classThis = /** @class */ (function () {
        function InsuranceClaim_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.claimNumber = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _claimNumber_initializers, void 0));
            this.billingId = (__runInitializers(this, _claimNumber_extraInitializers), __runInitializers(this, _billingId_initializers, void 0));
            this.insuranceId = (__runInitializers(this, _billingId_extraInitializers), __runInitializers(this, _insuranceId_initializers, void 0));
            this.insurance = (__runInitializers(this, _insuranceId_extraInitializers), __runInitializers(this, _insurance_initializers, void 0));
            this.patientId = (__runInitializers(this, _insurance_extraInitializers), __runInitializers(this, _patientId_initializers, void 0));
            this.claimType = (__runInitializers(this, _patientId_extraInitializers), __runInitializers(this, _claimType_initializers, void 0));
            this.status = (__runInitializers(this, _claimType_extraInitializers), __runInitializers(this, _status_initializers, void 0));
            this.payerClaimNumber = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _payerClaimNumber_initializers, void 0));
            this.clearinghouseClaimId = (__runInitializers(this, _payerClaimNumber_extraInitializers), __runInitializers(this, _clearinghouseClaimId_initializers, void 0));
            this.serviceStartDate = (__runInitializers(this, _clearinghouseClaimId_extraInitializers), __runInitializers(this, _serviceStartDate_initializers, void 0));
            this.serviceEndDate = (__runInitializers(this, _serviceStartDate_extraInitializers), __runInitializers(this, _serviceEndDate_initializers, void 0));
            this.submittedAt = (__runInitializers(this, _serviceEndDate_extraInitializers), __runInitializers(this, _submittedAt_initializers, void 0));
            this.acceptedAt = (__runInitializers(this, _submittedAt_extraInitializers), __runInitializers(this, _acceptedAt_initializers, void 0));
            this.adjudicatedAt = (__runInitializers(this, _acceptedAt_extraInitializers), __runInitializers(this, _adjudicatedAt_initializers, void 0));
            this.billedAmount = (__runInitializers(this, _adjudicatedAt_extraInitializers), __runInitializers(this, _billedAmount_initializers, void 0));
            this.allowedAmount = (__runInitializers(this, _billedAmount_extraInitializers), __runInitializers(this, _allowedAmount_initializers, void 0));
            this.paidAmount = (__runInitializers(this, _allowedAmount_extraInitializers), __runInitializers(this, _paidAmount_initializers, void 0));
            this.adjustmentAmount = (__runInitializers(this, _paidAmount_extraInitializers), __runInitializers(this, _adjustmentAmount_initializers, void 0));
            this.patientResponsibility = (__runInitializers(this, _adjustmentAmount_extraInitializers), __runInitializers(this, _patientResponsibility_initializers, void 0));
            this.coinsuranceAmount = (__runInitializers(this, _patientResponsibility_extraInitializers), __runInitializers(this, _coinsuranceAmount_initializers, void 0));
            this.copayAmount = (__runInitializers(this, _coinsuranceAmount_extraInitializers), __runInitializers(this, _copayAmount_initializers, void 0));
            this.deductibleAmount = (__runInitializers(this, _copayAmount_extraInitializers), __runInitializers(this, _deductibleAmount_initializers, void 0));
            this.diagnosisCodes = (__runInitializers(this, _deductibleAmount_extraInitializers), __runInitializers(this, _diagnosisCodes_initializers, void 0));
            this.procedureCodes = (__runInitializers(this, _diagnosisCodes_extraInitializers), __runInitializers(this, _procedureCodes_initializers, void 0));
            this.provider = (__runInitializers(this, _procedureCodes_extraInitializers), __runInitializers(this, _provider_initializers, void 0));
            this.facility = (__runInitializers(this, _provider_extraInitializers), __runInitializers(this, _facility_initializers, void 0));
            this.subscriber = (__runInitializers(this, _facility_extraInitializers), __runInitializers(this, _subscriber_initializers, void 0));
            this.patient = (__runInitializers(this, _subscriber_extraInitializers), __runInitializers(this, _patient_initializers, void 0));
            this.edi837Payload = (__runInitializers(this, _patient_extraInitializers), __runInitializers(this, _edi837Payload_initializers, void 0));
            this.edi835Response = (__runInitializers(this, _edi837Payload_extraInitializers), __runInitializers(this, _edi835Response_initializers, void 0));
            this.submissionHistory = (__runInitializers(this, _edi835Response_extraInitializers), __runInitializers(this, _submissionHistory_initializers, void 0));
            this.remarkCodes = (__runInitializers(this, _submissionHistory_extraInitializers), __runInitializers(this, _remarkCodes_initializers, void 0));
            this.adjustmentCodes = (__runInitializers(this, _remarkCodes_extraInitializers), __runInitializers(this, _adjustmentCodes_initializers, void 0));
            this.notes = (__runInitializers(this, _adjustmentCodes_extraInitializers), __runInitializers(this, _notes_initializers, void 0));
            this.submissionAttempts = (__runInitializers(this, _notes_extraInitializers), __runInitializers(this, _submissionAttempts_initializers, void 0));
            this.timelyFilingDeadline = (__runInitializers(this, _submissionAttempts_extraInitializers), __runInitializers(this, _timelyFilingDeadline_initializers, void 0));
            this.denials = (__runInitializers(this, _timelyFilingDeadline_extraInitializers), __runInitializers(this, _denials_initializers, void 0));
            this.createdAt = (__runInitializers(this, _denials_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            __runInitializers(this, _updatedAt_extraInitializers);
        }
        return InsuranceClaim_1;
    }());
    __setFunctionName(_classThis, "InsuranceClaim");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _claimNumber_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 50, unique: true }), (0, typeorm_1.Index)()];
        _billingId_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 100 }), (0, typeorm_1.Index)()];
        _insuranceId_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 100 }), (0, typeorm_1.Index)()];
        _insurance_decorators = [(0, typeorm_1.ManyToOne)(function () { return insurance_entity_1.Insurance; }, function (insurance) { return insurance.claims; }), (0, typeorm_1.JoinColumn)({ name: 'insuranceId' })];
        _patientId_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 100 }), (0, typeorm_1.Index)()];
        _claimType_decorators = [(0, typeorm_1.Column)({
                type: 'varchar',
                enum: enums_1.ClaimType,
                default: enums_1.ClaimType.PROFESSIONAL,
            })];
        _status_decorators = [(0, typeorm_1.Column)({
                type: 'varchar',
                enum: enums_1.ClaimStatus,
                default: enums_1.ClaimStatus.DRAFT,
            }), (0, typeorm_1.Index)()];
        _payerClaimNumber_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 50, nullable: true })];
        _clearinghouseClaimId_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 50, nullable: true })];
        _serviceStartDate_decorators = [(0, typeorm_1.Column)({ type: 'date' })];
        _serviceEndDate_decorators = [(0, typeorm_1.Column)({ type: 'date' })];
        _submittedAt_decorators = [(0, typeorm_1.Column)({ type: 'datetime', nullable: true })];
        _acceptedAt_decorators = [(0, typeorm_1.Column)({ type: 'datetime', nullable: true })];
        _adjudicatedAt_decorators = [(0, typeorm_1.Column)({ type: 'datetime', nullable: true })];
        _billedAmount_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _allowedAmount_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _paidAmount_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _adjustmentAmount_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _patientResponsibility_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _coinsuranceAmount_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _copayAmount_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _deductibleAmount_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 12, scale: 2, default: 0 })];
        _diagnosisCodes_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _procedureCodes_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _provider_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _facility_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _subscriber_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _patient_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _edi837Payload_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _edi835Response_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _submissionHistory_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _remarkCodes_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _adjustmentCodes_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _notes_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _submissionAttempts_decorators = [(0, typeorm_1.Column)({ type: 'integer', default: 0 })];
        _timelyFilingDeadline_decorators = [(0, typeorm_1.Column)({ type: 'date', nullable: true })];
        _denials_decorators = [(0, typeorm_1.OneToMany)(function () { return claim_denial_entity_1.ClaimDenial; }, function (denial) { return denial.claim; })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)()];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)()];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _claimNumber_decorators, { kind: "field", name: "claimNumber", static: false, private: false, access: { has: function (obj) { return "claimNumber" in obj; }, get: function (obj) { return obj.claimNumber; }, set: function (obj, value) { obj.claimNumber = value; } }, metadata: _metadata }, _claimNumber_initializers, _claimNumber_extraInitializers);
        __esDecorate(null, null, _billingId_decorators, { kind: "field", name: "billingId", static: false, private: false, access: { has: function (obj) { return "billingId" in obj; }, get: function (obj) { return obj.billingId; }, set: function (obj, value) { obj.billingId = value; } }, metadata: _metadata }, _billingId_initializers, _billingId_extraInitializers);
        __esDecorate(null, null, _insuranceId_decorators, { kind: "field", name: "insuranceId", static: false, private: false, access: { has: function (obj) { return "insuranceId" in obj; }, get: function (obj) { return obj.insuranceId; }, set: function (obj, value) { obj.insuranceId = value; } }, metadata: _metadata }, _insuranceId_initializers, _insuranceId_extraInitializers);
        __esDecorate(null, null, _insurance_decorators, { kind: "field", name: "insurance", static: false, private: false, access: { has: function (obj) { return "insurance" in obj; }, get: function (obj) { return obj.insurance; }, set: function (obj, value) { obj.insurance = value; } }, metadata: _metadata }, _insurance_initializers, _insurance_extraInitializers);
        __esDecorate(null, null, _patientId_decorators, { kind: "field", name: "patientId", static: false, private: false, access: { has: function (obj) { return "patientId" in obj; }, get: function (obj) { return obj.patientId; }, set: function (obj, value) { obj.patientId = value; } }, metadata: _metadata }, _patientId_initializers, _patientId_extraInitializers);
        __esDecorate(null, null, _claimType_decorators, { kind: "field", name: "claimType", static: false, private: false, access: { has: function (obj) { return "claimType" in obj; }, get: function (obj) { return obj.claimType; }, set: function (obj, value) { obj.claimType = value; } }, metadata: _metadata }, _claimType_initializers, _claimType_extraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: function (obj) { return "status" in obj; }, get: function (obj) { return obj.status; }, set: function (obj, value) { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
        __esDecorate(null, null, _payerClaimNumber_decorators, { kind: "field", name: "payerClaimNumber", static: false, private: false, access: { has: function (obj) { return "payerClaimNumber" in obj; }, get: function (obj) { return obj.payerClaimNumber; }, set: function (obj, value) { obj.payerClaimNumber = value; } }, metadata: _metadata }, _payerClaimNumber_initializers, _payerClaimNumber_extraInitializers);
        __esDecorate(null, null, _clearinghouseClaimId_decorators, { kind: "field", name: "clearinghouseClaimId", static: false, private: false, access: { has: function (obj) { return "clearinghouseClaimId" in obj; }, get: function (obj) { return obj.clearinghouseClaimId; }, set: function (obj, value) { obj.clearinghouseClaimId = value; } }, metadata: _metadata }, _clearinghouseClaimId_initializers, _clearinghouseClaimId_extraInitializers);
        __esDecorate(null, null, _serviceStartDate_decorators, { kind: "field", name: "serviceStartDate", static: false, private: false, access: { has: function (obj) { return "serviceStartDate" in obj; }, get: function (obj) { return obj.serviceStartDate; }, set: function (obj, value) { obj.serviceStartDate = value; } }, metadata: _metadata }, _serviceStartDate_initializers, _serviceStartDate_extraInitializers);
        __esDecorate(null, null, _serviceEndDate_decorators, { kind: "field", name: "serviceEndDate", static: false, private: false, access: { has: function (obj) { return "serviceEndDate" in obj; }, get: function (obj) { return obj.serviceEndDate; }, set: function (obj, value) { obj.serviceEndDate = value; } }, metadata: _metadata }, _serviceEndDate_initializers, _serviceEndDate_extraInitializers);
        __esDecorate(null, null, _submittedAt_decorators, { kind: "field", name: "submittedAt", static: false, private: false, access: { has: function (obj) { return "submittedAt" in obj; }, get: function (obj) { return obj.submittedAt; }, set: function (obj, value) { obj.submittedAt = value; } }, metadata: _metadata }, _submittedAt_initializers, _submittedAt_extraInitializers);
        __esDecorate(null, null, _acceptedAt_decorators, { kind: "field", name: "acceptedAt", static: false, private: false, access: { has: function (obj) { return "acceptedAt" in obj; }, get: function (obj) { return obj.acceptedAt; }, set: function (obj, value) { obj.acceptedAt = value; } }, metadata: _metadata }, _acceptedAt_initializers, _acceptedAt_extraInitializers);
        __esDecorate(null, null, _adjudicatedAt_decorators, { kind: "field", name: "adjudicatedAt", static: false, private: false, access: { has: function (obj) { return "adjudicatedAt" in obj; }, get: function (obj) { return obj.adjudicatedAt; }, set: function (obj, value) { obj.adjudicatedAt = value; } }, metadata: _metadata }, _adjudicatedAt_initializers, _adjudicatedAt_extraInitializers);
        __esDecorate(null, null, _billedAmount_decorators, { kind: "field", name: "billedAmount", static: false, private: false, access: { has: function (obj) { return "billedAmount" in obj; }, get: function (obj) { return obj.billedAmount; }, set: function (obj, value) { obj.billedAmount = value; } }, metadata: _metadata }, _billedAmount_initializers, _billedAmount_extraInitializers);
        __esDecorate(null, null, _allowedAmount_decorators, { kind: "field", name: "allowedAmount", static: false, private: false, access: { has: function (obj) { return "allowedAmount" in obj; }, get: function (obj) { return obj.allowedAmount; }, set: function (obj, value) { obj.allowedAmount = value; } }, metadata: _metadata }, _allowedAmount_initializers, _allowedAmount_extraInitializers);
        __esDecorate(null, null, _paidAmount_decorators, { kind: "field", name: "paidAmount", static: false, private: false, access: { has: function (obj) { return "paidAmount" in obj; }, get: function (obj) { return obj.paidAmount; }, set: function (obj, value) { obj.paidAmount = value; } }, metadata: _metadata }, _paidAmount_initializers, _paidAmount_extraInitializers);
        __esDecorate(null, null, _adjustmentAmount_decorators, { kind: "field", name: "adjustmentAmount", static: false, private: false, access: { has: function (obj) { return "adjustmentAmount" in obj; }, get: function (obj) { return obj.adjustmentAmount; }, set: function (obj, value) { obj.adjustmentAmount = value; } }, metadata: _metadata }, _adjustmentAmount_initializers, _adjustmentAmount_extraInitializers);
        __esDecorate(null, null, _patientResponsibility_decorators, { kind: "field", name: "patientResponsibility", static: false, private: false, access: { has: function (obj) { return "patientResponsibility" in obj; }, get: function (obj) { return obj.patientResponsibility; }, set: function (obj, value) { obj.patientResponsibility = value; } }, metadata: _metadata }, _patientResponsibility_initializers, _patientResponsibility_extraInitializers);
        __esDecorate(null, null, _coinsuranceAmount_decorators, { kind: "field", name: "coinsuranceAmount", static: false, private: false, access: { has: function (obj) { return "coinsuranceAmount" in obj; }, get: function (obj) { return obj.coinsuranceAmount; }, set: function (obj, value) { obj.coinsuranceAmount = value; } }, metadata: _metadata }, _coinsuranceAmount_initializers, _coinsuranceAmount_extraInitializers);
        __esDecorate(null, null, _copayAmount_decorators, { kind: "field", name: "copayAmount", static: false, private: false, access: { has: function (obj) { return "copayAmount" in obj; }, get: function (obj) { return obj.copayAmount; }, set: function (obj, value) { obj.copayAmount = value; } }, metadata: _metadata }, _copayAmount_initializers, _copayAmount_extraInitializers);
        __esDecorate(null, null, _deductibleAmount_decorators, { kind: "field", name: "deductibleAmount", static: false, private: false, access: { has: function (obj) { return "deductibleAmount" in obj; }, get: function (obj) { return obj.deductibleAmount; }, set: function (obj, value) { obj.deductibleAmount = value; } }, metadata: _metadata }, _deductibleAmount_initializers, _deductibleAmount_extraInitializers);
        __esDecorate(null, null, _diagnosisCodes_decorators, { kind: "field", name: "diagnosisCodes", static: false, private: false, access: { has: function (obj) { return "diagnosisCodes" in obj; }, get: function (obj) { return obj.diagnosisCodes; }, set: function (obj, value) { obj.diagnosisCodes = value; } }, metadata: _metadata }, _diagnosisCodes_initializers, _diagnosisCodes_extraInitializers);
        __esDecorate(null, null, _procedureCodes_decorators, { kind: "field", name: "procedureCodes", static: false, private: false, access: { has: function (obj) { return "procedureCodes" in obj; }, get: function (obj) { return obj.procedureCodes; }, set: function (obj, value) { obj.procedureCodes = value; } }, metadata: _metadata }, _procedureCodes_initializers, _procedureCodes_extraInitializers);
        __esDecorate(null, null, _provider_decorators, { kind: "field", name: "provider", static: false, private: false, access: { has: function (obj) { return "provider" in obj; }, get: function (obj) { return obj.provider; }, set: function (obj, value) { obj.provider = value; } }, metadata: _metadata }, _provider_initializers, _provider_extraInitializers);
        __esDecorate(null, null, _facility_decorators, { kind: "field", name: "facility", static: false, private: false, access: { has: function (obj) { return "facility" in obj; }, get: function (obj) { return obj.facility; }, set: function (obj, value) { obj.facility = value; } }, metadata: _metadata }, _facility_initializers, _facility_extraInitializers);
        __esDecorate(null, null, _subscriber_decorators, { kind: "field", name: "subscriber", static: false, private: false, access: { has: function (obj) { return "subscriber" in obj; }, get: function (obj) { return obj.subscriber; }, set: function (obj, value) { obj.subscriber = value; } }, metadata: _metadata }, _subscriber_initializers, _subscriber_extraInitializers);
        __esDecorate(null, null, _patient_decorators, { kind: "field", name: "patient", static: false, private: false, access: { has: function (obj) { return "patient" in obj; }, get: function (obj) { return obj.patient; }, set: function (obj, value) { obj.patient = value; } }, metadata: _metadata }, _patient_initializers, _patient_extraInitializers);
        __esDecorate(null, null, _edi837Payload_decorators, { kind: "field", name: "edi837Payload", static: false, private: false, access: { has: function (obj) { return "edi837Payload" in obj; }, get: function (obj) { return obj.edi837Payload; }, set: function (obj, value) { obj.edi837Payload = value; } }, metadata: _metadata }, _edi837Payload_initializers, _edi837Payload_extraInitializers);
        __esDecorate(null, null, _edi835Response_decorators, { kind: "field", name: "edi835Response", static: false, private: false, access: { has: function (obj) { return "edi835Response" in obj; }, get: function (obj) { return obj.edi835Response; }, set: function (obj, value) { obj.edi835Response = value; } }, metadata: _metadata }, _edi835Response_initializers, _edi835Response_extraInitializers);
        __esDecorate(null, null, _submissionHistory_decorators, { kind: "field", name: "submissionHistory", static: false, private: false, access: { has: function (obj) { return "submissionHistory" in obj; }, get: function (obj) { return obj.submissionHistory; }, set: function (obj, value) { obj.submissionHistory = value; } }, metadata: _metadata }, _submissionHistory_initializers, _submissionHistory_extraInitializers);
        __esDecorate(null, null, _remarkCodes_decorators, { kind: "field", name: "remarkCodes", static: false, private: false, access: { has: function (obj) { return "remarkCodes" in obj; }, get: function (obj) { return obj.remarkCodes; }, set: function (obj, value) { obj.remarkCodes = value; } }, metadata: _metadata }, _remarkCodes_initializers, _remarkCodes_extraInitializers);
        __esDecorate(null, null, _adjustmentCodes_decorators, { kind: "field", name: "adjustmentCodes", static: false, private: false, access: { has: function (obj) { return "adjustmentCodes" in obj; }, get: function (obj) { return obj.adjustmentCodes; }, set: function (obj, value) { obj.adjustmentCodes = value; } }, metadata: _metadata }, _adjustmentCodes_initializers, _adjustmentCodes_extraInitializers);
        __esDecorate(null, null, _notes_decorators, { kind: "field", name: "notes", static: false, private: false, access: { has: function (obj) { return "notes" in obj; }, get: function (obj) { return obj.notes; }, set: function (obj, value) { obj.notes = value; } }, metadata: _metadata }, _notes_initializers, _notes_extraInitializers);
        __esDecorate(null, null, _submissionAttempts_decorators, { kind: "field", name: "submissionAttempts", static: false, private: false, access: { has: function (obj) { return "submissionAttempts" in obj; }, get: function (obj) { return obj.submissionAttempts; }, set: function (obj, value) { obj.submissionAttempts = value; } }, metadata: _metadata }, _submissionAttempts_initializers, _submissionAttempts_extraInitializers);
        __esDecorate(null, null, _timelyFilingDeadline_decorators, { kind: "field", name: "timelyFilingDeadline", static: false, private: false, access: { has: function (obj) { return "timelyFilingDeadline" in obj; }, get: function (obj) { return obj.timelyFilingDeadline; }, set: function (obj, value) { obj.timelyFilingDeadline = value; } }, metadata: _metadata }, _timelyFilingDeadline_initializers, _timelyFilingDeadline_extraInitializers);
        __esDecorate(null, null, _denials_decorators, { kind: "field", name: "denials", static: false, private: false, access: { has: function (obj) { return "denials" in obj; }, get: function (obj) { return obj.denials; }, set: function (obj, value) { obj.denials = value; } }, metadata: _metadata }, _denials_initializers, _denials_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        InsuranceClaim = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return InsuranceClaim = _classThis;
}();
exports.InsuranceClaim = InsuranceClaim;
