"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.RevenueReport = void 0;
var typeorm_1 = require("typeorm");
var RevenueReport = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('revenue_reports')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _reportType_decorators;
    var _reportType_initializers = [];
    var _reportType_extraInitializers = [];
    var _periodType_decorators;
    var _periodType_initializers = [];
    var _periodType_extraInitializers = [];
    var _periodStart_decorators;
    var _periodStart_initializers = [];
    var _periodStart_extraInitializers = [];
    var _periodEnd_decorators;
    var _periodEnd_initializers = [];
    var _periodEnd_extraInitializers = [];
    var _generatedAt_decorators;
    var _generatedAt_initializers = [];
    var _generatedAt_extraInitializers = [];
    var _totalCharges_decorators;
    var _totalCharges_initializers = [];
    var _totalCharges_extraInitializers = [];
    var _totalPayments_decorators;
    var _totalPayments_initializers = [];
    var _totalPayments_extraInitializers = [];
    var _totalAdjustments_decorators;
    var _totalAdjustments_initializers = [];
    var _totalAdjustments_extraInitializers = [];
    var _totalRefunds_decorators;
    var _totalRefunds_initializers = [];
    var _totalRefunds_extraInitializers = [];
    var _netRevenue_decorators;
    var _netRevenue_initializers = [];
    var _netRevenue_extraInitializers = [];
    var _outstandingAR_decorators;
    var _outstandingAR_initializers = [];
    var _outstandingAR_extraInitializers = [];
    var _arAging_decorators;
    var _arAging_initializers = [];
    var _arAging_extraInitializers = [];
    var _claimsSubmitted_decorators;
    var _claimsSubmitted_initializers = [];
    var _claimsSubmitted_extraInitializers = [];
    var _claimsPaid_decorators;
    var _claimsPaid_initializers = [];
    var _claimsPaid_extraInitializers = [];
    var _claimsDenied_decorators;
    var _claimsDenied_initializers = [];
    var _claimsDenied_extraInitializers = [];
    var _claimsPending_decorators;
    var _claimsPending_initializers = [];
    var _claimsPending_extraInitializers = [];
    var _cleanClaimRate_decorators;
    var _cleanClaimRate_initializers = [];
    var _cleanClaimRate_extraInitializers = [];
    var _denialRate_decorators;
    var _denialRate_initializers = [];
    var _denialRate_extraInitializers = [];
    var _collectionRate_decorators;
    var _collectionRate_initializers = [];
    var _collectionRate_extraInitializers = [];
    var _averageDaysToPayment_decorators;
    var _averageDaysToPayment_initializers = [];
    var _averageDaysToPayment_extraInitializers = [];
    var _averageDaysInAR_decorators;
    var _averageDaysInAR_initializers = [];
    var _averageDaysInAR_extraInitializers = [];
    var _payerMix_decorators;
    var _payerMix_initializers = [];
    var _payerMix_extraInitializers = [];
    var _topDenialReasons_decorators;
    var _topDenialReasons_initializers = [];
    var _topDenialReasons_extraInitializers = [];
    var _topProcedures_decorators;
    var _topProcedures_initializers = [];
    var _topProcedures_extraInitializers = [];
    var _providerPerformance_decorators;
    var _providerPerformance_initializers = [];
    var _providerPerformance_extraInitializers = [];
    var _monthlyTrend_decorators;
    var _monthlyTrend_initializers = [];
    var _monthlyTrend_extraInitializers = [];
    var _keyMetrics_decorators;
    var _keyMetrics_initializers = [];
    var _keyMetrics_extraInitializers = [];
    var _notes_decorators;
    var _notes_initializers = [];
    var _notes_extraInitializers = [];
    var _generatedBy_decorators;
    var _generatedBy_initializers = [];
    var _generatedBy_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var RevenueReport = _classThis = /** @class */ (function () {
        function RevenueReport_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.reportType = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _reportType_initializers, void 0));
            this.periodType = (__runInitializers(this, _reportType_extraInitializers), __runInitializers(this, _periodType_initializers, void 0));
            this.periodStart = (__runInitializers(this, _periodType_extraInitializers), __runInitializers(this, _periodStart_initializers, void 0));
            this.periodEnd = (__runInitializers(this, _periodStart_extraInitializers), __runInitializers(this, _periodEnd_initializers, void 0));
            this.generatedAt = (__runInitializers(this, _periodEnd_extraInitializers), __runInitializers(this, _generatedAt_initializers, void 0));
            this.totalCharges = (__runInitializers(this, _generatedAt_extraInitializers), __runInitializers(this, _totalCharges_initializers, void 0));
            this.totalPayments = (__runInitializers(this, _totalCharges_extraInitializers), __runInitializers(this, _totalPayments_initializers, void 0));
            this.totalAdjustments = (__runInitializers(this, _totalPayments_extraInitializers), __runInitializers(this, _totalAdjustments_initializers, void 0));
            this.totalRefunds = (__runInitializers(this, _totalAdjustments_extraInitializers), __runInitializers(this, _totalRefunds_initializers, void 0));
            this.netRevenue = (__runInitializers(this, _totalRefunds_extraInitializers), __runInitializers(this, _netRevenue_initializers, void 0));
            this.outstandingAR = (__runInitializers(this, _netRevenue_extraInitializers), __runInitializers(this, _outstandingAR_initializers, void 0));
            this.arAging = (__runInitializers(this, _outstandingAR_extraInitializers), __runInitializers(this, _arAging_initializers, void 0));
            this.claimsSubmitted = (__runInitializers(this, _arAging_extraInitializers), __runInitializers(this, _claimsSubmitted_initializers, void 0));
            this.claimsPaid = (__runInitializers(this, _claimsSubmitted_extraInitializers), __runInitializers(this, _claimsPaid_initializers, void 0));
            this.claimsDenied = (__runInitializers(this, _claimsPaid_extraInitializers), __runInitializers(this, _claimsDenied_initializers, void 0));
            this.claimsPending = (__runInitializers(this, _claimsDenied_extraInitializers), __runInitializers(this, _claimsPending_initializers, void 0));
            this.cleanClaimRate = (__runInitializers(this, _claimsPending_extraInitializers), __runInitializers(this, _cleanClaimRate_initializers, void 0));
            this.denialRate = (__runInitializers(this, _cleanClaimRate_extraInitializers), __runInitializers(this, _denialRate_initializers, void 0));
            this.collectionRate = (__runInitializers(this, _denialRate_extraInitializers), __runInitializers(this, _collectionRate_initializers, void 0));
            this.averageDaysToPayment = (__runInitializers(this, _collectionRate_extraInitializers), __runInitializers(this, _averageDaysToPayment_initializers, void 0));
            this.averageDaysInAR = (__runInitializers(this, _averageDaysToPayment_extraInitializers), __runInitializers(this, _averageDaysInAR_initializers, void 0));
            this.payerMix = (__runInitializers(this, _averageDaysInAR_extraInitializers), __runInitializers(this, _payerMix_initializers, void 0));
            this.topDenialReasons = (__runInitializers(this, _payerMix_extraInitializers), __runInitializers(this, _topDenialReasons_initializers, void 0));
            this.topProcedures = (__runInitializers(this, _topDenialReasons_extraInitializers), __runInitializers(this, _topProcedures_initializers, void 0));
            this.providerPerformance = (__runInitializers(this, _topProcedures_extraInitializers), __runInitializers(this, _providerPerformance_initializers, void 0));
            this.monthlyTrend = (__runInitializers(this, _providerPerformance_extraInitializers), __runInitializers(this, _monthlyTrend_initializers, void 0));
            this.keyMetrics = (__runInitializers(this, _monthlyTrend_extraInitializers), __runInitializers(this, _keyMetrics_initializers, void 0));
            this.notes = (__runInitializers(this, _keyMetrics_extraInitializers), __runInitializers(this, _notes_initializers, void 0));
            this.generatedBy = (__runInitializers(this, _notes_extraInitializers), __runInitializers(this, _generatedBy_initializers, void 0));
            this.createdAt = (__runInitializers(this, _generatedBy_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            __runInitializers(this, _updatedAt_extraInitializers);
        }
        return RevenueReport_1;
    }());
    __setFunctionName(_classThis, "RevenueReport");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _reportType_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 50 }), (0, typeorm_1.Index)()];
        _periodType_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 20 }), (0, typeorm_1.Index)()];
        _periodStart_decorators = [(0, typeorm_1.Column)({ type: 'date' }), (0, typeorm_1.Index)()];
        _periodEnd_decorators = [(0, typeorm_1.Column)({ type: 'date' })];
        _generatedAt_decorators = [(0, typeorm_1.Column)({ type: 'datetime' })];
        _totalCharges_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 14, scale: 2, default: 0 })];
        _totalPayments_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 14, scale: 2, default: 0 })];
        _totalAdjustments_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 14, scale: 2, default: 0 })];
        _totalRefunds_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 14, scale: 2, default: 0 })];
        _netRevenue_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 14, scale: 2, default: 0 })];
        _outstandingAR_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 14, scale: 2, default: 0 })];
        _arAging_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _claimsSubmitted_decorators = [(0, typeorm_1.Column)({ type: 'integer', default: 0 })];
        _claimsPaid_decorators = [(0, typeorm_1.Column)({ type: 'integer', default: 0 })];
        _claimsDenied_decorators = [(0, typeorm_1.Column)({ type: 'integer', default: 0 })];
        _claimsPending_decorators = [(0, typeorm_1.Column)({ type: 'integer', default: 0 })];
        _cleanClaimRate_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 5, scale: 2, default: 0 })];
        _denialRate_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 5, scale: 2, default: 0 })];
        _collectionRate_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 5, scale: 2, default: 0 })];
        _averageDaysToPayment_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 8, scale: 2, default: 0 })];
        _averageDaysInAR_decorators = [(0, typeorm_1.Column)({ type: 'decimal', precision: 8, scale: 2, default: 0 })];
        _payerMix_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _topDenialReasons_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _topProcedures_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _providerPerformance_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _monthlyTrend_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _keyMetrics_decorators = [(0, typeorm_1.Column)({ type: 'simple-json', nullable: true })];
        _notes_decorators = [(0, typeorm_1.Column)({ type: 'text', nullable: true })];
        _generatedBy_decorators = [(0, typeorm_1.Column)({ type: 'varchar', length: 100, nullable: true })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)()];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)()];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _reportType_decorators, { kind: "field", name: "reportType", static: false, private: false, access: { has: function (obj) { return "reportType" in obj; }, get: function (obj) { return obj.reportType; }, set: function (obj, value) { obj.reportType = value; } }, metadata: _metadata }, _reportType_initializers, _reportType_extraInitializers);
        __esDecorate(null, null, _periodType_decorators, { kind: "field", name: "periodType", static: false, private: false, access: { has: function (obj) { return "periodType" in obj; }, get: function (obj) { return obj.periodType; }, set: function (obj, value) { obj.periodType = value; } }, metadata: _metadata }, _periodType_initializers, _periodType_extraInitializers);
        __esDecorate(null, null, _periodStart_decorators, { kind: "field", name: "periodStart", static: false, private: false, access: { has: function (obj) { return "periodStart" in obj; }, get: function (obj) { return obj.periodStart; }, set: function (obj, value) { obj.periodStart = value; } }, metadata: _metadata }, _periodStart_initializers, _periodStart_extraInitializers);
        __esDecorate(null, null, _periodEnd_decorators, { kind: "field", name: "periodEnd", static: false, private: false, access: { has: function (obj) { return "periodEnd" in obj; }, get: function (obj) { return obj.periodEnd; }, set: function (obj, value) { obj.periodEnd = value; } }, metadata: _metadata }, _periodEnd_initializers, _periodEnd_extraInitializers);
        __esDecorate(null, null, _generatedAt_decorators, { kind: "field", name: "generatedAt", static: false, private: false, access: { has: function (obj) { return "generatedAt" in obj; }, get: function (obj) { return obj.generatedAt; }, set: function (obj, value) { obj.generatedAt = value; } }, metadata: _metadata }, _generatedAt_initializers, _generatedAt_extraInitializers);
        __esDecorate(null, null, _totalCharges_decorators, { kind: "field", name: "totalCharges", static: false, private: false, access: { has: function (obj) { return "totalCharges" in obj; }, get: function (obj) { return obj.totalCharges; }, set: function (obj, value) { obj.totalCharges = value; } }, metadata: _metadata }, _totalCharges_initializers, _totalCharges_extraInitializers);
        __esDecorate(null, null, _totalPayments_decorators, { kind: "field", name: "totalPayments", static: false, private: false, access: { has: function (obj) { return "totalPayments" in obj; }, get: function (obj) { return obj.totalPayments; }, set: function (obj, value) { obj.totalPayments = value; } }, metadata: _metadata }, _totalPayments_initializers, _totalPayments_extraInitializers);
        __esDecorate(null, null, _totalAdjustments_decorators, { kind: "field", name: "totalAdjustments", static: false, private: false, access: { has: function (obj) { return "totalAdjustments" in obj; }, get: function (obj) { return obj.totalAdjustments; }, set: function (obj, value) { obj.totalAdjustments = value; } }, metadata: _metadata }, _totalAdjustments_initializers, _totalAdjustments_extraInitializers);
        __esDecorate(null, null, _totalRefunds_decorators, { kind: "field", name: "totalRefunds", static: false, private: false, access: { has: function (obj) { return "totalRefunds" in obj; }, get: function (obj) { return obj.totalRefunds; }, set: function (obj, value) { obj.totalRefunds = value; } }, metadata: _metadata }, _totalRefunds_initializers, _totalRefunds_extraInitializers);
        __esDecorate(null, null, _netRevenue_decorators, { kind: "field", name: "netRevenue", static: false, private: false, access: { has: function (obj) { return "netRevenue" in obj; }, get: function (obj) { return obj.netRevenue; }, set: function (obj, value) { obj.netRevenue = value; } }, metadata: _metadata }, _netRevenue_initializers, _netRevenue_extraInitializers);
        __esDecorate(null, null, _outstandingAR_decorators, { kind: "field", name: "outstandingAR", static: false, private: false, access: { has: function (obj) { return "outstandingAR" in obj; }, get: function (obj) { return obj.outstandingAR; }, set: function (obj, value) { obj.outstandingAR = value; } }, metadata: _metadata }, _outstandingAR_initializers, _outstandingAR_extraInitializers);
        __esDecorate(null, null, _arAging_decorators, { kind: "field", name: "arAging", static: false, private: false, access: { has: function (obj) { return "arAging" in obj; }, get: function (obj) { return obj.arAging; }, set: function (obj, value) { obj.arAging = value; } }, metadata: _metadata }, _arAging_initializers, _arAging_extraInitializers);
        __esDecorate(null, null, _claimsSubmitted_decorators, { kind: "field", name: "claimsSubmitted", static: false, private: false, access: { has: function (obj) { return "claimsSubmitted" in obj; }, get: function (obj) { return obj.claimsSubmitted; }, set: function (obj, value) { obj.claimsSubmitted = value; } }, metadata: _metadata }, _claimsSubmitted_initializers, _claimsSubmitted_extraInitializers);
        __esDecorate(null, null, _claimsPaid_decorators, { kind: "field", name: "claimsPaid", static: false, private: false, access: { has: function (obj) { return "claimsPaid" in obj; }, get: function (obj) { return obj.claimsPaid; }, set: function (obj, value) { obj.claimsPaid = value; } }, metadata: _metadata }, _claimsPaid_initializers, _claimsPaid_extraInitializers);
        __esDecorate(null, null, _claimsDenied_decorators, { kind: "field", name: "claimsDenied", static: false, private: false, access: { has: function (obj) { return "claimsDenied" in obj; }, get: function (obj) { return obj.claimsDenied; }, set: function (obj, value) { obj.claimsDenied = value; } }, metadata: _metadata }, _claimsDenied_initializers, _claimsDenied_extraInitializers);
        __esDecorate(null, null, _claimsPending_decorators, { kind: "field", name: "claimsPending", static: false, private: false, access: { has: function (obj) { return "claimsPending" in obj; }, get: function (obj) { return obj.claimsPending; }, set: function (obj, value) { obj.claimsPending = value; } }, metadata: _metadata }, _claimsPending_initializers, _claimsPending_extraInitializers);
        __esDecorate(null, null, _cleanClaimRate_decorators, { kind: "field", name: "cleanClaimRate", static: false, private: false, access: { has: function (obj) { return "cleanClaimRate" in obj; }, get: function (obj) { return obj.cleanClaimRate; }, set: function (obj, value) { obj.cleanClaimRate = value; } }, metadata: _metadata }, _cleanClaimRate_initializers, _cleanClaimRate_extraInitializers);
        __esDecorate(null, null, _denialRate_decorators, { kind: "field", name: "denialRate", static: false, private: false, access: { has: function (obj) { return "denialRate" in obj; }, get: function (obj) { return obj.denialRate; }, set: function (obj, value) { obj.denialRate = value; } }, metadata: _metadata }, _denialRate_initializers, _denialRate_extraInitializers);
        __esDecorate(null, null, _collectionRate_decorators, { kind: "field", name: "collectionRate", static: false, private: false, access: { has: function (obj) { return "collectionRate" in obj; }, get: function (obj) { return obj.collectionRate; }, set: function (obj, value) { obj.collectionRate = value; } }, metadata: _metadata }, _collectionRate_initializers, _collectionRate_extraInitializers);
        __esDecorate(null, null, _averageDaysToPayment_decorators, { kind: "field", name: "averageDaysToPayment", static: false, private: false, access: { has: function (obj) { return "averageDaysToPayment" in obj; }, get: function (obj) { return obj.averageDaysToPayment; }, set: function (obj, value) { obj.averageDaysToPayment = value; } }, metadata: _metadata }, _averageDaysToPayment_initializers, _averageDaysToPayment_extraInitializers);
        __esDecorate(null, null, _averageDaysInAR_decorators, { kind: "field", name: "averageDaysInAR", static: false, private: false, access: { has: function (obj) { return "averageDaysInAR" in obj; }, get: function (obj) { return obj.averageDaysInAR; }, set: function (obj, value) { obj.averageDaysInAR = value; } }, metadata: _metadata }, _averageDaysInAR_initializers, _averageDaysInAR_extraInitializers);
        __esDecorate(null, null, _payerMix_decorators, { kind: "field", name: "payerMix", static: false, private: false, access: { has: function (obj) { return "payerMix" in obj; }, get: function (obj) { return obj.payerMix; }, set: function (obj, value) { obj.payerMix = value; } }, metadata: _metadata }, _payerMix_initializers, _payerMix_extraInitializers);
        __esDecorate(null, null, _topDenialReasons_decorators, { kind: "field", name: "topDenialReasons", static: false, private: false, access: { has: function (obj) { return "topDenialReasons" in obj; }, get: function (obj) { return obj.topDenialReasons; }, set: function (obj, value) { obj.topDenialReasons = value; } }, metadata: _metadata }, _topDenialReasons_initializers, _topDenialReasons_extraInitializers);
        __esDecorate(null, null, _topProcedures_decorators, { kind: "field", name: "topProcedures", static: false, private: false, access: { has: function (obj) { return "topProcedures" in obj; }, get: function (obj) { return obj.topProcedures; }, set: function (obj, value) { obj.topProcedures = value; } }, metadata: _metadata }, _topProcedures_initializers, _topProcedures_extraInitializers);
        __esDecorate(null, null, _providerPerformance_decorators, { kind: "field", name: "providerPerformance", static: false, private: false, access: { has: function (obj) { return "providerPerformance" in obj; }, get: function (obj) { return obj.providerPerformance; }, set: function (obj, value) { obj.providerPerformance = value; } }, metadata: _metadata }, _providerPerformance_initializers, _providerPerformance_extraInitializers);
        __esDecorate(null, null, _monthlyTrend_decorators, { kind: "field", name: "monthlyTrend", static: false, private: false, access: { has: function (obj) { return "monthlyTrend" in obj; }, get: function (obj) { return obj.monthlyTrend; }, set: function (obj, value) { obj.monthlyTrend = value; } }, metadata: _metadata }, _monthlyTrend_initializers, _monthlyTrend_extraInitializers);
        __esDecorate(null, null, _keyMetrics_decorators, { kind: "field", name: "keyMetrics", static: false, private: false, access: { has: function (obj) { return "keyMetrics" in obj; }, get: function (obj) { return obj.keyMetrics; }, set: function (obj, value) { obj.keyMetrics = value; } }, metadata: _metadata }, _keyMetrics_initializers, _keyMetrics_extraInitializers);
        __esDecorate(null, null, _notes_decorators, { kind: "field", name: "notes", static: false, private: false, access: { has: function (obj) { return "notes" in obj; }, get: function (obj) { return obj.notes; }, set: function (obj, value) { obj.notes = value; } }, metadata: _metadata }, _notes_initializers, _notes_extraInitializers);
        __esDecorate(null, null, _generatedBy_decorators, { kind: "field", name: "generatedBy", static: false, private: false, access: { has: function (obj) { return "generatedBy" in obj; }, get: function (obj) { return obj.generatedBy; }, set: function (obj, value) { obj.generatedBy = value; } }, metadata: _metadata }, _generatedBy_initializers, _generatedBy_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        RevenueReport = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return RevenueReport = _classThis;
}();
exports.RevenueReport = RevenueReport;
